### PR TITLE
Fix: Serve schema from github so to speed the mesh build

### LINKED ISSUE #68: Gateway: mesh build is slow
Mesh build is slow, leading to a slow restart of the gateway when the credentials are added or updated.

### PR DESCRIPTION
**Pull request by saimanoj**
https://github.com/poozlehq/engine/issues/68

### CODE REVIEW

File: engine-server/src/main.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ async function bootstrap() {
   // Cors
   if (corsConfig.enabled) {
     app.enableCors({
-      origin: configService.get('FRONTEND_HOST').split(','),
+      origin: configService.get('FRONTEND_HOST')? configService.get('FRONTEND_HOST').split(','): '',
```
Comment (harshithmullapudi) [inline engine-server/src/main.ts]:
```js
configService.get('FRONTEND_HOST') || ""
```

File: engine-server/src/modules/extension_account/extension_account.utils.ts [hunk 2]
```diff
@@ -1,3 +1,3 @@
 /** Copyright (c) 2023, Poozle, all rights reserved. **/
 
-export function getSpecForExtensionAccount(extensionAccountName: string) {}
```
Comment (harshithmullapudi) [inline engine-server/src/modules/extension_account/extension_account.utils.ts:3]: why are we commenting this line?

Comment (saimanoj) [reply engine-server/src/modules/extension_account/extension_account.utils.ts:3]: This is failing when building the server and we are not using it anywhere, afaik. Am I missing something here

**Review by harshithmullapudi — APPROVED** [review]
